# Events:
# ApplicationStop, BeforeInstall, AfterInstall, ApplicationStart, ValidateService
# https://docs.aws.amazon.com/codedeploy/latest/APIReference/API_LifecycleEvent.html
version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/aws-codedeploy-bitbucket-laravel
hooks:
  AfterInstall:
    - location: ./devops/hooks/after-install.sh
      runas: ubuntu

#BeforeInstall
#AfterInstall